### ISSUE TITLE
failed to GET http://google.com: Get "http://google.com": context deadline exceeded

### ISSUE THREAD

**Issue by anhtrung87vn** [hhorai/gnbsim#18] opened 2020-10-22 02:20 UTC
Hi Horai,

I setup a model as below: 
1 PC that has 2 interfaces 10.250.40.5(internal) and 10.250.176.15(can access internet) to install gNBsim
1 PC that has 2 interfaces 10.250.40.6(internal) and 10.250.176.14(can access internet) to install free5GC.

gNBsim(10.250.40.5 for signaling and gtpu)--------------AMF(10.250.40.6)------UPF(10.250.40.6 for gtpu---->10.250.176.14 forward to internet)

When run gNBsim with interface 10.250.176.15 enabled: 
The result is good:

> gnbsim]2020/10/22 08:55:55.227880 example.go:88: write: len 40, info: &{Stream:0 SSN:4 Flags:0 _:0 PPID:1006632960 Context:0 TTL:0 TSN:35366810 CumTSN:0 AssocID:4}
> [gnbsim]2020/10/22 08:55:58.228198 example.go:216: test: GTPuIFname: ens8
> [gnbsim]2020/10/22 08:55:58.228309 example.go:217: test: GTP-U Peer: 10.250.40.6
> [gnbsim]2020/10/22 08:55:58.228324 example.go:218: test: GTP-U Peer TEID: 1
> [gnbsim]2020/10/22 08:55:58.228333 example.go:219: test: GTP-U Local TEID: 2596996162
> [gnbsim]2020/10/22 08:55:58.228363 example.go:220: test: UE address: 60.60.0.1
> test: gNB UDP local address: 10.250.40.5:2152
> runUPlane
> [gnbsim]2020/10/22 08:56:03.524713 example.go:402: [HTTP Probe] Successfully GET http://google.com: Status: 200 OK
> [gnbsim]2020/10/22 08:56:08.675702 example.go:402: [HTTP Probe] Successfully GET http://google.com: Status: 200 OK
> [gnbsim]2020/10/22 08:56:13.824313 example.go:402: [HTTP Probe] Successfully GET http://google.com: Status: 200 OK
> [gnbsim]2020/10/22 08:56:19.023841 example.go:402: [HTTP Probe] Successfully GET http://google.com: Status: 200 OK

From wireshark trace, I see that the packets go through the tunnel  10.250.40.5 -> 10.250.40.6

But when I disable the interface 10.250.176.15(can access internet) , it failed due to errors below and I don't any gtp packets sent out.

> gnbsim]2020/10/22 09:16:01.526970 example.go:88: write: len 40, info: &{Stream:0 SSN:4 Flags:0 _:0 PPID:1006632960 Context:0 TTL:0 TSN:3158309692 CumTSN:0 AssocID:3}
> [gnbsim]2020/10/22 09:16:04.527478 example.go:216: test: GTPuIFname: ens8
> [gnbsim]2020/10/22 09:16:04.527581 example.go:217: test: GTP-U Peer: 10.250.40.6
> [gnbsim]2020/10/22 09:16:04.527600 example.go:218: test: GTP-U Peer TEID: 5
> [gnbsim]2020/10/22 09:16:04.527625 example.go:219: test: GTP-U Local TEID: 2596996162
> [gnbsim]2020/10/22 09:16:04.527640 example.go:220: test: UE address: 60.60.0.3
> test: gNB UDP local address: 10.250.40.5:2152
> runUPlane
> [gnbsim]2020/10/22 09:16:12.553160 example.go:397: failed to GET http://google.com: Get "http://google.com": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

Do you know what problem in this case?

Thanks,
Trung.

**Comment by hhorai** [comment] 2020-10-23 16:54
Hi, @anhtrung87vn 

Thank you for using gnbsim.
I would like to check `ip addr` command output on the gnbsim server.
Could you share the information with us?

**Comment by anhtrung87vn** [comment] 2020-10-23 23:45
> 
> 
> Hi, @anhtrung87vn
> 
> Thank you for using gnbsim.
> I would like to check `ip addr` command output on the gnbsim server.
> Could you share the information with us?

**Comment by anhtrung87vn** [comment] 2020-10-23 23:46
> 
> 
> Hi, @anhtrung87vn
> 
> Thank you for using gnbsim.
> I would like to check `ip addr` command output on the gnbsim server.
> Could you share the information with us?

Hi

**Comment by hhorai** [comment] 2020-10-24 16:36
Thank you for sharing the log.
The configuration seems to be good. Unfortunately I have not found the root cause for now.

**Comment by anhtrung87vn** [comment] 2020-10-24 17:03
Thank Horai.

**Comment by hhorai** [comment] 2020-10-26 14:24
Hi, @anhtrung87vn 

Thank you. It makes sense.
If you do not mind, could you close this issue?

**Closed** 2020-10-26 22:20 UTC
