### ISSUE TITLE
Modification for free5gc v3.0.4

### ISSUE THREAD

**Issue by shigeki-yamano** [hhorai/gnbsim#12] opened 2020-10-06 01:19 UTC
the current gnbsim sends NGAP messages to free5gc v3.0.4's AMF as follows.

- gnb -> AMF : NGSetupRequest
- gNB <- AMF : NGSetupResponse
- gNB -> AMF : InitialUEMessage(Registration Request)
- gNB <- AMF : DLNAS(Authentication Request)
- gNB -> AMF : ULNAS(Authentication Response)
- gNB <- AMF : DLNAS(Security mode Command)
- gNB -> AMF : ULNAS(Security mode Complete)
- gNB <- AMF : DLNAS(Registraion Accept)
- gNB -> AMF : InitialContextSetupResponse
- gNB -> AMF : ULNAS (Registration Complete)
- gNB -> AMF : ULNAS (PDU Session Establishment Request)
- gNB <- AMF : InitialContextSetupRequest
- gNB -> AMF : PDUSessionResourceSetupResponse

In my code review,
free5gc v3.0.4's AMF returns Registration Accept on DLNAS
if INITIAL UE MESSAGE does not include UE Context Request IE.

If gnbsim needs to receive Registration Accept on Initial Context Setup Request,
gnbsim should send INITIAL UE MESSAGE which contains UE Context Request IE, I think.

**TS 38.413/8.6.1 Initial UE Message**

```
If the UE Context Request IE is included in the INITIAL UE MESSAGE message 
the AMF shall trigger an Initial Context Setup procedure towards the NG-RAN node.
```

**Comment by hhorai** [comment] 2020-10-06 17:20
@shigeki-yamano 

Thanks you for letting me know.
I have checked my code and found that it is completely a bug.
Now the problem is fixed in hhorai/gnbsim@dba215f.

Thanks again.

**Closed** 2020-10-07 01:31 UTC
